################################# Default configuration ###################
baseURL = "https://web.bmauri.com/"
title = "Básculas Mauri | Grupo Mauri"
theme = "bmauri-theme"
DefaultContentLanguage = "es"
languageCode = "es-es"

# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ['fr', 'cat']


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "about"
URL = "about"
weight = 1

[[menu.main]]
name = "project"
URL = "project"
weight = 2

[[menu.main]]
name = "service"
URL = "service"
weight = 3


# [[menu.main]]
# name = "blog"
# URL = "blog"
# weight = 4

# [[menu.main]]
# weight = 5
# name = "pages"
# hasChildren = true
#
#   [[menu.main]]
#   parent = "pages"
#   name = "FAQ"
#   URL = "faq"
#
#   [[menu.main]]
#   parent = "pages"
#   name = "pricing"
#   URL = "pricing"

[[menu.main]]
name = "contact"
URL = "contact"
weight = 6


# footer menu
[[menu.footer]]
name = "about"
URL = "about"
weight = 1

[[menu.footer]]
name = "project"
URL = "project"
weight = 2

[[menu.footer]]
name = "service"
URL = "service"
weight = 3

# [[menu.footer]]
# name = "pricing"
# URL = "pricing"
# weight = 4
#
# [[menu.footer]]
# name = "FAQ"
# URL = "faq"
# weight = 5

[[menu.footer]]
name = "contact"
URL = "contact"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Básculas Mauri, profesionales de la industria del pesaje."
author = "Grupo Mauri"
# Contact Information
mobile = "+34 902 21 20 85"
phone = "+34 902 21 20 85"
email = "info@bmauri.com"
location = "Avinguda dels Països Catalans, 28 Local B, Tarragona"
# contact form action
contact_form_action = "https://formspree.io/oriol@bmauri.com" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

# Navigation get start button
[params.nav_button]
enable = true
label = "Llamar"
link = "contact"

# google map
[params.gmap]
enable = true
iframe = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d751.2612041974269!2d1.2461614881218739!3d41.13354759869918!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12a3fd2222e7cd13%3A0x60c510bdd5f5827c!2sB%C3%A1sculas%20Mauri!5e0!3m2!1ses!2ses!4v1583401980221!5m2!1ses!2ses"


############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

################################ France Language ########################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2
home = "Inicio"
# copyright
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"

################################ France Language ########################
[Languages.cat]
languageName = "Cat"
languageCode = "cat-cat"
contentDir = "content/catalan"
weight = 2
home = "Inici"
# copyright
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
